// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sonaar.Domain.DataContexts;

#nullable disable

namespace Sonaar.Domain.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241211124106_AddedFirmBank")]
    partial class AddedFirmBank
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sonaar.Domain.Entities.Authentication.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sonaar.Domain.Entities.Contacts.ContactDetails", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContactId"));

                    b.Property<string>("AdharNumber")
                        .HasColumnType("text");

                    b.Property<string>("ContactAddress1")
                        .HasColumnType("text");

                    b.Property<string>("ContactAddress2")
                        .HasColumnType("text");

                    b.Property<string>("ContactCity")
                        .HasColumnType("text");

                    b.Property<string>("ContactFirstName")
                        .HasColumnType("text");

                    b.Property<string>("ContactLandMark")
                        .HasColumnType("text");

                    b.Property<string>("ContactLastName")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ContactPinCode")
                        .HasColumnType("text");

                    b.Property<string>("ContactPrifix")
                        .HasColumnType("text");

                    b.Property<string>("ContactState")
                        .HasColumnType("text");

                    b.Property<int>("ContactType")
                        .HasColumnType("integer");

                    b.Property<string>("CustmorCountry")
                        .HasColumnType("text");

                    b.Property<string>("CustmorGSTNumber")
                        .HasColumnType("text");

                    b.Property<string>("CustmorZipCode")
                        .HasColumnType("text");

                    b.Property<string>("PanNumber")
                        .HasColumnType("text");

                    b.HasKey("ContactId");

                    b.ToTable("ContactDetails");
                });

            modelBuilder.Entity("Sonaar.Domain.Entities.Global.FirmEntities", b =>
                {
                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FirmId"));

                    b.Property<string>("AccountHolder")
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("FirmAddress")
                        .HasColumnType("text");

                    b.Property<string>("FirmGSTNumber")
                        .HasColumnType("text");

                    b.Property<string>("FirmName")
                        .HasColumnType("text");

                    b.Property<string>("FirmPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("IfscCode")
                        .HasColumnType("text");

                    b.HasKey("FirmId");

                    b.ToTable("FirmEntities");
                });

            modelBuilder.Entity("Sonaar.Domain.Entities.PreSale.PreSaleEntity", b =>
                {
                    b.Property<int>("PreSaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PreSaleId"));

                    b.Property<int>("BillType")
                        .HasColumnType("integer");

                    b.Property<int>("Billid")
                        .HasColumnType("integer");

                    b.Property<int?>("ContactId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateofBill")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GstAmountId")
                        .HasColumnType("integer");

                    b.HasKey("PreSaleId");

                    b.HasIndex("ContactId");

                    b.HasIndex("GstAmountId");

                    b.ToTable("PreSaleEntities");
                });

            modelBuilder.Entity("Sonaar.Domain.Entities.Product.ProductEntity", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("HSN_Code")
                        .HasColumnType("text");

                    b.Property<decimal>("Making_Charge")
                        .HasColumnType("numeric");

                    b.Property<string>("Purity")
                        .HasColumnType("text");

                    b.Property<int>("QuotationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("ProductId");

                    b.HasIndex("QuotationId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Sonaar.Domain.Entities.Quotations.GstAmountEntity", b =>
                {
                    b.Property<int>("GstAmountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GstAmountId"));

                    b.Property<decimal>("CGSt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IGST")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SGST")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAfterDiscount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalBeforeDiscount")
                        .HasColumnType("numeric");

                    b.HasKey("GstAmountId");

                    b.ToTable("GstAmountEntity");
                });

            modelBuilder.Entity("Sonaar.Domain.Entities.Quotations.Quotation", b =>
                {
                    b.Property<int>("QuotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuotationId"));

                    b.Property<int>("BillType")
                        .HasColumnType("integer");

                    b.Property<int>("Billid")
                        .HasColumnType("integer");

                    b.Property<int?>("ContactId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateofBill")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GstAmountId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean");

                    b.HasKey("QuotationId");

                    b.HasIndex("ContactId");

                    b.HasIndex("GstAmountId");

                    b.ToTable("Quotations");
                });

            modelBuilder.Entity("Sonaar.Domain.Entities.PreSale.PreSaleEntity", b =>
                {
                    b.HasOne("Sonaar.Domain.Entities.Contacts.ContactDetails", "ContactDetails")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("Sonaar.Domain.Entities.Quotations.GstAmountEntity", "GSTAmount")
                        .WithMany()
                        .HasForeignKey("GstAmountId");

                    b.Navigation("ContactDetails");

                    b.Navigation("GSTAmount");
                });

            modelBuilder.Entity("Sonaar.Domain.Entities.Product.ProductEntity", b =>
                {
                    b.HasOne("Sonaar.Domain.Entities.PreSale.PreSaleEntity", "PreSaleEntity")
                        .WithMany("ProductList")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sonaar.Domain.Entities.Quotations.Quotation", "Quotation")
                        .WithMany("ProductList")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreSaleEntity");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("Sonaar.Domain.Entities.Quotations.Quotation", b =>
                {
                    b.HasOne("Sonaar.Domain.Entities.Contacts.ContactDetails", "ContactDetails")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("Sonaar.Domain.Entities.Quotations.GstAmountEntity", "GSTAmount")
                        .WithMany()
                        .HasForeignKey("GstAmountId");

                    b.Navigation("ContactDetails");

                    b.Navigation("GSTAmount");
                });

            modelBuilder.Entity("Sonaar.Domain.Entities.PreSale.PreSaleEntity", b =>
                {
                    b.Navigation("ProductList");
                });

            modelBuilder.Entity("Sonaar.Domain.Entities.Quotations.Quotation", b =>
                {
                    b.Navigation("ProductList");
                });
#pragma warning restore 612, 618
        }
    }
}
